# Generated by Django 5.1.7 on 2025-03-23 08:11

import django.db.models.deletion
import post_generator.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class", max_length=100
                    ),
                ),
                ("max_text_length", models.PositiveIntegerField(default=280)),
                (
                    "image_aspect_ratio",
                    models.CharField(
                        default="1:1", help_text="Format: width:height", max_length=20
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("promotional", "Promotional"),
                            ("informational", "Informational"),
                            ("engagement", "Engagement"),
                            ("announcement", "Announcement"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "template_text",
                    models.TextField(help_text="Use {variables} for dynamic content"),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object with variable names as keys and descriptions as values",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(default="#FFFFFF", max_length=20),
                ),
                ("text_color", models.CharField(default="#000000", max_length=20)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("variables_used", models.JSONField(default=dict)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=post_generator.models.post_image_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("schedule_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_generator.platform",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_generator.posttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "default_hashtags",
                    models.TextField(
                        blank=True, help_text="Enter hashtags separated by spaces"
                    ),
                ),
                (
                    "preferred_platforms",
                    models.ManyToManyField(blank=True, to="post_generator.platform"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
